name: Make JDK (Android)
run-name: Make JDK ${{ inputs.jdk_version }} (Android)
on:
  workflow_dispatch:
    inputs:
      jdk_version:
        description: "OpenJDK feature version"
        required: true
        default: "25"
      ndk_version:
        description: "Official NDK version for the android clang"
        required: true
        default: "27"
      ndk_revision:
        description: "Official NDK revision letter (optional)"
        required: false
        default: "d"

permissions:
  contents: write
  packages: read

jobs:
  make:
    uses: ./.github/workflows/make-jdk.yml
    secrets: inherit
    with:
      platform: android
      jdk_version: ${{ inputs.jdk_version }}
      ndk_version: ${{ inputs.ndk_version }}
      ndk_revision: ${{ inputs.ndk_revision }}
      # riscv64-linux-android
      targets: '["aarch64-linux-android", "armv7a-linux-androideabi", "i686-linux-android", "x86_64-linux-android"]'
